### pip install pyyaml ###
### config for fetal_head_segmentation

data_path: data/us_dataset
data_split: [0.8, 0.2] # train/test split
lr: 0.01 # learning rate for Adam optimizer
wt_dec: 0.0001 # weight decay rate
num_epochs: 100 # epochs to train
batch_size: 4 # training batch size
device: cuda # cuda or cpu
is_batchnorm: False # whether perform batchnorm after conv layer
feature_scale: 4 # down scale the filter numbers
